### ISSUE TITLE
Error in production using combined hooks

### ISSUE THREAD

**Issue by RuneSP** [pdtec/ngx-observable-lifecycle#1]
When I compile using ng build --prod I get an error that ngOnInit$ is undefined when extending BaseHooks$ or AllHooks$. Extending OnInit$ or OnDestroy$ individually works fine. 

I import all from "@pdtec/ngx-observable-lifecycle" and using Angular 9 with ivy.

**Comment by pburgmer** [comment]
Sorry for delay. Problem has been fixed now. I just released a new version 2.0.1.
